# Generated by Django 5.2.8 on 2025-11-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cohere_api_key',
            field=models.CharField(blank=True, help_text="User's personal Cohere API key (optional)", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='groq_api_key',
            field=models.CharField(blank=True, help_text="User's personal Groq API key (optional)", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_cohere_model',
            field=models.CharField(blank=True, default='command-r', help_text='Preferred Cohere model', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_gemini_model',
            field=models.CharField(blank=True, default='models/gemini-2.5-flash', help_text='Preferred Gemini model', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_groq_model',
            field=models.CharField(blank=True, default='llama-3.3-70b-versatile', help_text='Preferred Groq model', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('groq', 'Groq'), ('cohere', 'Cohere')], default='gemini', help_text='Preferred AI provider', max_length=20),
        ),
    ]
