# Generated by Django 5.2.8 on 2025-11-05 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_model', models.CharField(default='gpt-4', max_length=100)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=2000)),
                ('enable_sentiment_analysis', models.BooleanField(default=True)),
                ('enable_topic_extraction', models.BooleanField(default=True)),
                ('enable_semantic_search', models.BooleanField(default=True)),
                ('analysis_depth', models.CharField(choices=[('basic', 'Basic'), ('detailed', 'Detailed'), ('comprehensive', 'Comprehensive')], default='detailed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configurations',
            },
        ),
        migrations.CreateModel(
            name='EmbeddingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('text_preview', models.CharField(max_length=200)),
                ('embedding', models.JSONField()),
                ('model', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('access_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-last_accessed'],
                'indexes': [models.Index(fields=['text_hash'], name='ai_service__text_ha_de45b5_idx'), models.Index(fields=['-last_accessed'], name='ai_service__last_ac_f48b9b_idx')],
            },
        ),
    ]
